[[redirects]]
from = "https://survey.frontendbr.com.br"
to = "https://frontendbr-survey.netlify.com"
status = 200

[[redirects]]
from = "https://eventos.frontendbr.com.br"
to = "https://frontendbr.github.io/eventos"
status = 200
